apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080

          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: GIN_MODE
              value: "{{ .Values.env.GIN_MODE }}"

          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config

          resources:
{{ toYaml .Values.resources | indent 12 }}

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3