# .github/workflows/lab3.yml
name: Lab 3 Kubernetes Deployment

on: [push]

jobs:
  kind-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install KinD
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind --version

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Create KinD cluster
      run: |
        kind create cluster --name lab3 --wait 60s
        kubectl cluster-info

    - name: Apply manifests
      run: |
        kubectl apply -f k8s/

    - name: Wait for pods
      run: |
        kubectl wait --for=condition=Ready pod -l app=ecommerce --timeout=120s --ignore-not-found
        kubectl wait --for=condition=Ready pod -l app=postgres --timeout=120s --ignore-not-found

    - name: Run Lab 3 Grading Script
      run: |
        chmod +x ./tests/lab3_test.sh
        ./tests/lab3_test.sh